---

- name: TestAnsibleLocal
  gather_facts: true
  hosts: all
#  become: true
#  Do not assume root, to execute playbooks over command bus
#  Used for verifying if Ansible is running locally on a Morpheus appliance
  connection: local
  tasks: 
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - debug:
        var: ansible_hostname
    - debug:
        var: ansible_all_ipv4_addresses
    - debug:
        var: ansible_distribution
